spring:
  application:
    name: aec-auth
  datasource:
    url: ${DATASOURCE_URL} # Sin valor por defecto
    username: ${DATASOURCE_USER} # Sin valor por defecto
    password: ${DATASOURCE_PASS} # Sin valor por defecto
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # 'update' puede ser un valor por defecto seguro para desarrollo local si es lo que usas

jwt:
  secret: ${JWT_SECRET} # ¡MUY IMPORTANTE! Sin valor por defecto
  accessMs: ${JWT_ACCESS_MS:3600000} # Puedes mantener valores por defecto para duraciones si son consistentes
  refreshMs: ${JWT_REFRESH_MS:86400000} # Puedes mantener valores por defecto para duraciones si son consistentes

server:
  port: ${SERVER_PORT:8082} # Un valor por defecto para el puerto está bien para desarrollo local

docker:
  compose:
    enabled: false
