spring:
  application:
    name: aec-auth # Nombre de la aplicación

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

    show-sql: true # Útil para depuración. Considera 'false' en producción.
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect # Siempre especifica el dialecto

jwt:
  secret: ${JWT_SECRET} 
  accessMs: ${JWT_ACCESS_MS:3600000} # Las duraciones pueden tener valores por defecto
  refreshMs: ${JWT_REFRESH_MS:86400000} # Las duraciones pueden tener valores por defecto

server:
  port: ${PORT:8080}


docker:
  compose:
    enabled: false 
